format = """\
[╭╴](fg:os)\
$os\
$username\
$shell\
(\
    $directory\
)\
(\
    $git_branch\
    $git_status\
)\
(\
    $dotnet\
    $lua\
    $nodejs\
    $php\
    $python\
    $ruby\
)\
$cmd_duration
[╰─](fg:os)$character\
"""
add_newline = true
palette = "normal"

[os]
disabled = false
style = "fg:$os"

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
EndeavourOS = ""
Fedora = "󰣛"
Gentoo = "󰣨"
Kali = ""
Linux = "󰌽"
Macos = "󰀵"
Manjaro = ""
Mint = "󰣭"
NixOS = ""
Pop = ""
Raspbian = ""
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Unknown = "󰆍"
Windows = "󰍲"

[username]
style_user = "bold user"
style_root = "bold user_root"
format = " [$user](fg:$style) "
disabled = false
show_always = true

[shell]
disabled = false
format = '[ $indicator: ]($style)'
bash_indicator = "bash"
fish_indicator = "fish"
zsh_indicator = "zsh"
powershell_indicator = "powershell"
pwsh_indicator = "pwsh"
ion_indicator = "ion"
elvish_indicator = "elvish"
tcsh_indicator = "tcsh"
xonsh_indicator = "xonsh"
cmd_indicator = "cmd"
nu_indicator = "nu"
unknown_indicator = ""
style = "fg:shell"

[directory]
format = "[at]($style) [$path](bold $style)[$read_only]($read_only_style) "
truncation_length = 3
style = "fg:directory"
read_only_style = "fg:directory"
repo_root_style = "fg:directory bold"
before_repo_root_style = "fg:directory"
truncation_symbol = "…/"
truncate_to_repo = false
read_only ="  "
home_symbol = ""

[git_branch]
format = "[$symbol $branch]($style) "
style = "bold fg:git"
symbol = ""

[git_status]
format = '([$ahead_behind]($style) )([$all_status]($style) )'
style = "fg:git"
stashed = "*${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
up_to_date = ""
diverged = "⇡${ahead_count}⇣${behind_count}"
conflicted = "=${count}"
deleted = "×${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
ignore_submodules = false
disabled = false

[dotnet]
disabled =  false
format = "[](fg:dotnet)[$symbol( $version)]($style)[](fg:dotnet)"
heuristic = false
style = "bg:dotnet fg:text_color"
symbol = ".NET"

[lua]
disabled = false
format ="[](fg:lua)[$symbol( $version)]($style)[](fg:lua)"
style = "bg:lua fg:text_color"
symbol = ""

[nodejs]
disabled = false
format = "[](fg:node)[$symbol( $version)]($style)[](fg:node)"
style = "bg:node fg:text_color"
symbol = ""
version_format = "${raw}"

[php]
disabled = false
format = "[](fg:php)[$symbol( $version)]($style)[](fg:php)"
style = "bg:php fg:text_color"
symbol = ""

[python]
disabled = false
format = "[](fg:python)[$symbol( $pyenv_prefix)( $version)( $virtualenv)]($style)[](fg:python)"
symbol = ""
style = "bg:python fg:text_light"
version_format = "${raw}"

[ruby]
disabled = false
format = "[](fg:rails)[$symbol( $version)]($style)[](fg:rails)"
style = "bg:rails fg:text_color"
symbol = ""
version_format = "${raw}"

[cmd_duration]
format = " [󱫑 $duration]($style) "
style = "bold fg:duration"
min_time = 1
disabled = false

[character]
disabled = false
success_symbol = "[❯](bold fg:style)"
error_symbol = "[❯](bold fg:red)"
vimcmd_symbol = "[❮](bold fg:style)"
vimcmd_replace_one_symbol = "[❮](bold fg:lavender)"
vimcmd_replace_symbol = "[❮](bold fg:lavender)"
vimcmd_visual_symbol = "[❮](bold fg:yellow)"

[fill]
symbol = " "

[time]
disabled = true
format = "at [󱑈 $time]($style)"
time_format = "%H:%M"
style = "bold fg:time"

[docker_context]
disabled=true
symbol = " "

[package]
disabled=true

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.normal]
style = "#cdd6f4"
os = "#cdd6f4"
user = "#89b4fa"
user_root = "#f38ba8"
shell = "#a6adc8"
directory = "#fab387"
git = "#94e2d5"
git_status = "#94e2d5"

dotnet = "#512bd4"
lua = "#000080"
node = "#417e38"
php = "#4F5B93"
python = "#ffd343"
rails = "#D30001"

duration = "#7f849c"
text_color = "#cdd6f4"
text_light = "#7f849c"

time = "#b4befe"
